add_newline = true

# [character]
# success_symbol = "[ﬦ](bold green)"
# error_symbol = "[ﬦ](bold red)"

# [package]
# symbol = " "
#
# [nodejs]
# symbol = " "
#
[git_branch]
symbol= " "
# symbol = "🌱 "
#
[golang]
symbol = "ﳑ "
#
# [aws]
# format = ''
