source ~/dotfiles/homefiles/aliases
source ~/Google\ Drive/My\ Drive/dotprivate/private

# Node version manager fnm
eval "$(fnm env --use-on-cd)"

# Zoxide
eval "$(zoxide init zsh)"

# exit vim mode with jj
bindkey -M viins 'jj' vi-cmd-mode

# Set go path
export GOPATH=~/.gocode

# Editor
export EDITOR=nvim
# Pager
export PAGER=bat

# PATH
export PATH="$PATH:$HOME/dotfiles/bin" # add local scripts to path
export PATH="$PATH:$HOME/Google Drive/My Drive/dotprivate/bin" # add local scripts to path
export PATH="$PATH:$HOME/Sites/awstools" # add local scripts to path
export PATH="/usr/local/bin:$PATH" # local before everything else
export PATH="$PATH:$HOME/.composer/vendor/bin" # add composer in path for global dependencies
export PATH="$PATH:$HOME/.rvm/bin" # add RVM to PATH for scripting
export PATH="$PATH:$HOME/.gocode/bin" # Add go scripts
export PATH=$HOME/.tmux/plugins/t-smart-tmux-session-manager/bin:$PATH #~/.tmux/plugins
export PATH="$PATH:$HOME/.local/bin" # pipx

# zsh autosuggestions
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
# zsh syntax highlight
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# zsh substring history
source /opt/homebrew/share/zsh-history-substring-search/zsh-history-substring-search.zsh
bindkey '^P' history-substring-search-up
bindkey '^N' history-substring-search-down

# history
setopt share_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_verify

# completion
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"

eval "$(starship init zsh)"

# bun completions
[ -s "/Users/aleksandar/.bun/_bun" ] && source "/Users/aleksandar/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# bat (theme follows ~/.theme)
if [[ -f ~/.theme ]] && [[ "$(cat ~/.theme)" == "light" ]]; then
  export BAT_THEME="Catppuccin Latte"
else
  export BAT_THEME="Catppuccin Mocha"
fi

eval "$(hx init zsh)"
